#!/usr/bin/env python3
"""
generate_schema_rb.py

Consumes the parsed table state produced by parse_spree_migrations.py and emits:
  1. spree_schema_full.json  -- one row per column with type + nullability
                                 (parse_spree_migrations.py's own JSON export only
                                 keeps column NAMES, not full detail, since that
                                 script's original purpose was just the summary
                                 counts printed to stdout)
  2. spree_schema.rb         -- a single consolidated ActiveRecord::Schema.define
                                 file: the schema.rb Spree does not ship natively,
                                 since Spree core is a Rails ENGINE (a gem), not a
                                 full application -- engines have no db/schema.rb of
                                 their own; the schema only exists as the sequence of
                                 migration files a host app runs. This reconstructs
                                 that sequence's cumulative result.

Run: python3 generate_schema_rb.py
Requires parse_spree_migrations.py in the same directory (imported, not re-run via
subprocess, so both scripts share one parse pass).

KNOWN LIMITATIONS, stated plainly (see also parse_spree_migrations.py's own docstring
for parser-level limitations this script inherits):
  - Column types are as declared in the migration DSL (e.g. "string", "integer",
    "decimal"), not resolved to full SQL types with precision/scale.
  - Reference columns (t.references / t.belongs_to) are rendered as plain
    `t.bigint "..._id"`, the concrete column Rails actually creates.
  - DEFAULT values are not tracked.
  - Ruby conditionals inside migrations (e.g. `t.change :info, :jsonb, ... if
    t.respond_to?(:jsonb)` with a `:json` fallback branch) cannot be evaluated by a
    static text parser -- whichever branch's line appears LAST in the migration file
    wins, which may not match the type a real deployed database ends up with. This
    affects a small, documented number of columns (as of 2026-09-10: known to affect
    `spree_user_identities.info`, which the parser resolves to "json" rather than
    the "jsonb" a Postgres deployment supporting jsonb would actually use).
"""
import json
import re

from parse_spree_migrations import tables as parsed_tables


def build_full_export(parsed_tables):
    """Extract full per-column detail (type, nullability) for every active table."""
    active = {k: v for k, v in parsed_tables.items() if not v['dropped']}
    full = {}
    for name, t in active.items():
        full[name] = {
            'pk': t['pk'],
            'columns': {
                col: {'type': meta.get('type'), 'null_false': meta.get('null_false', False)}
                for col, meta in t['columns'].items()
            },
            'fks': sorted(t['fks']),
            'indexes': [{'unique': idx['unique'], 'cols': idx['cols']} for idx in t['indexes']],
            'checks': t['checks'],
        }
    return full


def clean_type(t):
    """Strip the parser's internal '(ref)' marker (used to distinguish reference
    columns during parsing) down to the real Rails column type, 'bigint'."""
    if not t:
        return 'string'
    if '(ref)' in t:
        return 'bigint'
    return t


def build_schema_rb(full_export):
    lines = []
    lines.append("# This file is auto-generated from Spree Commerce's Rails migrations")
    lines.append("# (spree/spree@main, squashed base migration 20210914000000_spree_four_three.rb")
    lines.append("# + 276 incremental migrations since).")
    lines.append("#")
    lines.append("# It is the schema.rb Spree does not ship natively, since Spree core is a Rails")
    lines.append("# ENGINE (a gem), not a full application -- engines have no db/schema.rb of their")
    lines.append("# own; the schema only exists as the sequence of migration files that a host app")
    lines.append("# runs. This file is that sequence's cumulative result, reconstructed by")
    lines.append("# parse_spree_migrations.py + generate_schema_rb.py (a heuristic Ruby-migration")
    lines.append("# parser), not generated by `rails db:schema:dump`.")
    lines.append("#")
    lines.append("# KNOWN LIMITATIONS -- see generate_schema_rb.py's module docstring for the full")
    lines.append("# list. The one affecting actual output: spree_user_identities.info's type")
    lines.append("# depends on a Ruby `if t.respond_to?(:jsonb)` conditional this parser cannot")
    lines.append("# evaluate; it resolves to whichever branch's line is LAST in the source file.")
    lines.append("#")
    lines.append("")
    lines.append("ActiveRecord::Schema.define do")
    lines.append("")

    for tname in sorted(full_export.keys()):
        t = full_export[tname]
        id_opt = '' if t['pk'] == 'id' else ', id: false'
        lines.append(f'  create_table "{tname}"{id_opt}, force: :cascade do |t|')
        for col, meta in t['columns'].items():
            ctype = clean_type(meta.get('type'))
            null_str = ', null: false' if meta.get('null_false') else ''
            lines.append(f'    t.{ctype} "{col}"{null_str}')
        for idx in t['indexes']:
            uniq = ', unique: true' if idx['unique'] else ''
            lines.append(f"    t.index {idx['cols']}{uniq}")
        for chk in t['checks']:
            chk_escaped = chk.replace('"', '\\"')
            lines.append(f'    t.check_constraint "{chk_escaped}"')
        lines.append('  end')
        lines.append('')

    for tname in sorted(full_export.keys()):
        for fk_ref in full_export[tname]['fks']:
            lines.append(f'  add_foreign_key "{tname}", "{fk_ref}"')

    lines.append('')
    lines.append('end')
    return '\n'.join(lines)


def main():
    full_export = build_full_export(parsed_tables)

    with open('spree_schema_full.json', 'w') as f:
        json.dump(full_export, f, indent=2)
    print(f"Wrote spree_schema_full.json: {len(full_export)} tables")

    schema_rb = build_schema_rb(full_export)
    with open('spree_schema.rb', 'w') as f:
        f.write(schema_rb)
    n_tables = schema_rb.count('create_table')
    n_fks = schema_rb.count('add_foreign_key')
    n_checks = schema_rb.count('check_constraint')
    print(f"Wrote spree_schema.rb: {n_tables} tables, {n_fks} FKs, {n_checks} CHECK constraints")


if __name__ == '__main__':
    main()
