"""A second explicit, documented exception to independence from
generator/ (alongside phase1_utility.py, see DESIGN.md): reads each case
study's raw schema JSON directly -- plain declarative DDL-equivalent
data (table columns, primary keys, foreign keys), produced by
all_schema_extraction/, not generated by the search or by Phase 1's own
DMN compilation. Reading it is no different from reading the DDL a real
database was built from; it carries no FEEL-translation or search-time
computation risk.

Never imports generator/compile_constraints.py's CASE_STUDY_SCHEMA_JSON
constant -- the file paths are re-declared here independently so this
module has zero import-time dependency on any generator/ Python code,
even though the underlying JSON files are (deliberately) the same ones.
"""
import json
import os

REPO_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')

SCHEMA_JSON_PATHS = {
    'FLEX2': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                           'output', 'flex2_schema_full.json'),
    'OpenMRS': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                             'output', 'openmrs_schema_full.json'),
    'Spree': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                           'output', 'spree_schema_full.json'),
    'jBilling': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                              'output', 'jbilling_schema_full.json'),
}

_CACHE = {}


def load_schema(case_study):
    if case_study not in _CACHE:
        with open(SCHEMA_JSON_PATHS[case_study], encoding='utf-8') as f:
            _CACHE[case_study] = json.load(f)
    return _CACHE[case_study]


def _table_entry(schema, table):
    return schema.get(table) or schema.get(table.upper()) or schema.get(table.lower())


def canonical_table_name(case_study, table):
    """The schema JSON's OWN casing for `table`, regardless of how the
    caller (or `variable_resolution`, which is not case-consistent with
    the schema extraction -- confirmed directly: FLEX2's own schema JSON
    uses STUDENT_PROGRAM/SEMESTER/COURSE_REGISTRATION while some compiled
    records reference the same tables lowercased) spelled it. Every join-
    path/root-picking comparison in this module goes through this first,
    so a casing mismatch is never mistaken for two different tables.
    Returns `table` unchanged if the schema has no matching entry at all
    (an actually-unknown table, not a casing issue)."""
    schema = load_schema(case_study)
    for candidate in (table, table.upper(), table.lower()):
        if candidate in schema:
            return candidate
    return table


def pk_column(case_study, table):
    entry = _table_entry(load_schema(case_study), table)
    return entry.get('pk') if entry else None


def fk_edges(case_study, table):
    """[{column, ref_table, ref_column}, ...] -- this table's own
    OUTGOING foreign keys, exactly as all_schema_extraction produced
    them. `ref_table` is normalized to the schema's own canonical casing
    (see `canonical_table_name`) so a caller can compare it directly
    against another canonicalized table name without a casing mismatch."""
    entry = _table_entry(load_schema(case_study), table)
    edges = (entry or {}).get('fk_columns', [])
    return [{**e, 'ref_table': canonical_table_name(case_study, e['ref_table'])} for e in edges]


def build_join_path(case_study, root_table, target_table, allowed_tables):
    """BFS over the FK graph, restricted to `allowed_tables` (a
    decision's own fk_closure_tables -- never wander through the whole
    schema), from `root_table` to `target_table`, following FK edges
    FORWARD ONLY -- a table's own outgoing FK column to another table's
    primary key. Deliberately one-directional: a BACKWARD join (some
    other table's FK pointing AT root_table) is one-to-many from
    root_table's own side -- "which of the many child rows" is a real
    ambiguity a single subject-row lookup cannot resolve without more
    context, so it is not attempted here (surfaces as an unresolved
    subject table, not a silently arbitrary pick -- see
    `subject_table.py`'s own `_pick_root`, which relies on this same
    forward-only restriction to disambiguate which table is the root in
    the first place). Returns a list of hops:
    [{'from_table','from_column','to_table','to_column'}, ...], root to
    target, or None if unreachable within `allowed_tables`. Root-to-root
    is an empty list, not None."""
    root_table = canonical_table_name(case_study, root_table)
    target_table = canonical_table_name(case_study, target_table)
    if root_table == target_table:
        return []

    allowed = {canonical_table_name(case_study, t) for t in allowed_tables} | {root_table, target_table}
    visited = {root_table}
    queue = [(root_table, [])]

    while queue:
        current, path = queue.pop(0)
        for edge in fk_edges(case_study, current):
            nxt = edge['ref_table']
            if nxt in allowed and nxt not in visited:
                hop = {'from_table': current, 'from_column': edge['column'],
                       'to_table': nxt, 'to_column': edge['ref_column']}
                new_path = path + [hop]
                if nxt == target_table:
                    return new_path
                visited.add(nxt)
                queue.append((nxt, new_path))
    return None
