"""A second explicit, documented exception to independence from
generator/ (alongside phase1_utility.py, see DESIGN.md): reads each case
study's raw schema JSON directly -- plain declarative DDL-equivalent
data (table columns, primary keys, foreign keys), produced by
all_schema_extraction/, not generated by the search or by Phase 1's own
DMN compilation. Reading it is no different from reading the DDL a real
database was built from; it carries no FEEL-translation or search-time
computation risk.

Never imports generator/compile_constraints.py's CASE_STUDY_SCHEMA_JSON
constant -- the file paths are re-declared here independently so this
module has zero import-time dependency on any generator/ Python code,
even though the underlying JSON files are (deliberately) the same ones.
"""
import json
import os

REPO_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')

SCHEMA_JSON_PATHS = {
    'FLEX2': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                           'output', 'flex2_schema_full.json'),
    'OpenMRS': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                             'output', 'openmrs_schema_full.json'),
    'Spree': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                           'output', 'spree_schema_full.json'),
    'jBilling': os.path.join(REPO_ROOT, 'all_schema_extraction', 'all_schema_extraction',
                              'output', 'jbilling_schema_full.json'),
}

_CACHE = {}


def load_schema(case_study):
    if case_study not in _CACHE:
        with open(SCHEMA_JSON_PATHS[case_study], encoding='utf-8') as f:
            _CACHE[case_study] = json.load(f)
    return _CACHE[case_study]


def _table_entry(schema, table):
    return schema.get(table) or schema.get(table.upper()) or schema.get(table.lower())


def canonical_table_name(case_study, table):
    """The schema JSON's OWN casing for `table`, regardless of how the
    caller (or `variable_resolution`, which is not case-consistent with
    the schema extraction -- confirmed directly: FLEX2's own schema JSON
    uses STUDENT_PROGRAM/SEMESTER/COURSE_REGISTRATION while some compiled
    records reference the same tables lowercased) spelled it. Every join-
    path/root-picking comparison in this module goes through this first,
    so a casing mismatch is never mistaken for two different tables.
    Returns `table` unchanged if the schema has no matching entry at all
    (an actually-unknown table, not a casing issue)."""
    schema = load_schema(case_study)
    for candidate in (table, table.upper(), table.lower()):
        if candidate in schema:
            return candidate
    return table


def pk_columns(case_study, table):
    """Always a list, even for a single-column PK -- normalizes the
    schema JSON's own `pk` field (a bare string for a single column, a
    list for a composite one, confirmed directly: FLEX2's
    COURSE_REGISTRATION/STUDENT_SEMESTER both have `pk: [...]` composite
    keys) so every caller handles exactly one shape."""
    entry = _table_entry(load_schema(case_study), table)
    pk = (entry or {}).get('pk')
    if pk is None:
        return []
    return pk if isinstance(pk, list) else [pk]


def fk_edges(case_study, table):
    """[{column, ref_table, ref_column}, ...] -- this table's own
    OUTGOING foreign keys, exactly as all_schema_extraction produced
    them, PLUS any disclosed `supplementary_fk_edges.py` entries for
    real FKs the extractor missed entirely (a real, pre-existing gap in
    Spree's own extraction -- confirmed several join/association tables
    have `fk_columns: []` despite an unambiguous real target by Rails
    convention). Supplementary edges are ADDITIVE, never a replacement
    for an extracted one -- disambiguating a wrong/ambiguous extracted
    edge is `join_disambiguation.py`'s own, separate job. `ref_table` is
    normalized to the schema's own canonical casing (see
    `canonical_table_name`) so a caller can compare it directly against
    another canonicalized table name without a casing mismatch."""
    from supplementary_fk_edges import get_supplementary_edges
    entry = _table_entry(load_schema(case_study), table)
    edges = list((entry or {}).get('fk_columns', [])) + get_supplementary_edges(case_study, table)
    return [{**e, 'ref_table': canonical_table_name(case_study, e['ref_table'])} for e in edges]


def functional_backward_edges(case_study, table):
    """Tables with a FUNCTIONAL (provably at-most-one-row) backward
    reference INTO `table`: some other table `S` has an FK column
    pointing at `table`, where `S`'s own PRIMARY KEY *is exactly* that FK
    column (a shared-PK subtype pattern -- confirmed real and common,
    not hypothetical: OpenMRS's own `concept_numeric` has PK `concept_id`
    AND an FK `concept_id -> concept.concept_id`; 6 such tables exist in
    OpenMRS's schema alone). This is SAFE to traverse backward: because
    S's PK equals the FK column, at most one S row can exist per `table`
    row -- there is no "which of the many child rows" ambiguity the way
    there is for an ordinary one-to-many backward FK (a genuinely
    one-to-many backward join is NOT attempted anywhere in this module;
    only this provably-unique special case is). Returns
    [{'column', 'ref_table', 'ref_column'}, ...] in the SAME shape
    `fk_edges` uses, so `build_join_path` can treat them uniformly."""
    schema = load_schema(case_study)
    target = canonical_table_name(case_study, table)
    found = []
    for other_name, info in schema.items():
        other_pk = info.get('pk')
        other_pk_list = other_pk if isinstance(other_pk, list) else ([other_pk] if other_pk else [])
        for fk in info.get('fk_columns', []):
            if canonical_table_name(case_study, fk['ref_table']) == target and other_pk_list == [fk['column']]:
                found.append({'column': fk['ref_column'], 'ref_table': other_name,
                              'ref_column': fk['column']})
    return found


def composite_backward_edges(case_study, table):
    """Tables T whose own COMPOSITE primary key (>=2 columns) can be
    reconstructed entirely from `table`'s own single-column FK values,
    because every one of T's PK columns is ITSELF an FK to the exact same
    (ref_table, ref_column) that some column of `table` already FKs to --
    a genuine, schema-declared value correspondence, never a guess:
    `table` and T both independently FK to the same real entity in each
    PK slot, and T's own PK then guarantees at most one T row shares all
    of them. Confirmed real, not hypothetical (both found investigating
    FLEX2's own backward-join gaps, 2026-09-25): STUDENT_PROGRAM's own
    `(BATCH_NO, PROG_ID)` FK values exactly match BATCH_PROGRAM's own
    composite PK `(BATCH_NO, PROG_ID)` (both FK to BATCH.BATCH_NO/
    PROGRAM.PROG_ID respectively); COURSE_REGISTRATION's own
    `(SEM_ID, ROLL_NO)` FK values exactly match STUDENT_SEMESTER's own
    composite PK the same way. This is deliberately NOT the same
    mechanism as `build_join_path`'s ordinary single-column hop (walking
    ONE FK to ONE PK column) -- it combines SEVERAL of `table`'s own
    already-known FK columns into ONE match against a multi-column target
    key, which no single-column hop chain can express at all.

    Returns [{'columns': [...], 'ref_table': T, 'ref_columns': [...]}],
    `columns`/`ref_columns` in the SAME order (T's own PK column order),
    one entry per qualifying T. Never fires for a single-column PK (that
    table is already reachable, if at all, via the ordinary forward-FK
    BFS -- no need to duplicate it here)."""
    schema = load_schema(case_study)
    table = canonical_table_name(case_study, table)
    source_targets = {(e['ref_table'], e['ref_column']): e['column']
                       for e in fk_edges(case_study, table)}

    found = []
    for other_name in schema:
        other_name = canonical_table_name(case_study, other_name)
        if other_name == table:
            continue
        pk = pk_columns(case_study, other_name)
        if len(pk) < 2:
            continue
        other_fk_target_by_column = {e['column']: (e['ref_table'], e['ref_column'])
                                      for e in fk_edges(case_study, other_name)}
        matched_columns = []
        for pk_col in pk:
            target = other_fk_target_by_column.get(pk_col)
            source_column = source_targets.get(target) if target else None
            if source_column is None:
                matched_columns = None
                break
            matched_columns.append(source_column)
        if matched_columns and len(set(matched_columns)) == len(matched_columns):
            found.append({'columns': matched_columns, 'ref_table': other_name, 'ref_columns': pk})
    return found


def build_join_path(case_study, root_table, target_table, allowed_tables):
    """BFS over the FK graph, restricted to `allowed_tables` (a
    decision's own fk_closure_tables -- never wander through the whole
    schema), from `root_table` to `target_table`. Follows FK edges
    FORWARD (a table's own outgoing FK column to another table's primary
    key) and, additionally, FUNCTIONAL BACKWARD edges
    (`functional_backward_edges` -- a shared-PK subtype table, provably
    at most one matching row, never a real one-to-many ambiguity).

    An ORDINARY backward join (some other table's FK pointing AT the
    current table, where that other table's PK is NOT the FK column --
    genuinely one-to-many) is deliberately never attempted here: "which
    of the many child rows" is a real ambiguity a single subject-row
    lookup cannot resolve without more context, so it surfaces as an
    unresolved subject table, not a silently arbitrary pick (see
    `subject_table.py`'s own `_pick_root`, which relies on this same
    restriction to disambiguate which table is the root in the first
    place). Returns a list of hops:
    [{'from_table','from_column','to_table','to_column'}, ...], root to
    target, or None if unreachable within `allowed_tables`. Root-to-root
    is an empty list, not None."""
    root_table = canonical_table_name(case_study, root_table)
    target_table = canonical_table_name(case_study, target_table)
    if root_table == target_table:
        return []

    allowed = {canonical_table_name(case_study, t) for t in allowed_tables} | {root_table, target_table}
    visited = {root_table}
    queue = [(root_table, [])]
    skipped_ambiguous = []

    while queue:
        current, path = queue.pop(0)
        edges = fk_edges(case_study, current) + functional_backward_edges(case_study, current)

        # A real bug found testing this against OpenMRS's own obs/concept
        # tables: `obs` has TWO distinct FK columns to `concept`
        # (`concept_id` -- which concept this observation measures --
        # and `value_coded` -- an unrelated coded ANSWER value). Picking
        # either one silently, by iteration order, can silently join
        # through the WRONG column. Group by target table first; more
        # than one distinct column reaching the same table is SKIPPED
        # (never traversed), not arbitrarily resolved -- an ambiguous
        # edge irrelevant to the actual target (e.g. every table's own
        # audit-trail FKs to `users`) must never abort the whole search;
        # it only matters if the target turns out unreachable without it.
        by_target = {}
        for edge in edges:
            nxt = edge['ref_table']
            if nxt in allowed and nxt not in visited:
                by_target.setdefault(nxt, []).append(edge)

        for nxt, candidate_edges in by_target.items():
            distinct_columns = {e['column'] for e in candidate_edges}
            if len(distinct_columns) > 1:
                from join_disambiguation import get_override
                override = get_override(case_study, current, nxt)
                if override is None:
                    skipped_ambiguous.append((current, nxt, sorted(distinct_columns)))
                    continue
                matching = [e for e in candidate_edges if e['column'] == override['column']]
                if not matching:
                    raise ValueError(
                        f"join_disambiguation override for ({case_study!r}, {current!r}, "
                        f"{nxt!r}) names column {override['column']!r}, which is not among "
                        f"the actual distinct columns found ({sorted(distinct_columns)}) -- "
                        f"the override is stale, fix it rather than silently ignoring it.")
                candidate_edges = matching
            edge = candidate_edges[0]
            hop = {'from_table': current, 'from_column': edge['column'],
                   'to_table': nxt, 'to_column': edge['ref_column']}
            new_path = path + [hop]
            if nxt == target_table:
                # A second real bug, found testing the FIRST fix above:
                # skipping the ambiguous obs->concept edge let BFS
                # silently route around it via obs->location->concept
                # instead -- an indirect path that happens to be
                # technically valid but semantically nonsensical (a
                # location's own "location type concept" has nothing to
                # do with what an observation measures). Silently
                # rerouting around a skipped ambiguity is WORSE than
                # refusing outright. So: refuse this path too if any
                # skipped ambiguous edge connects two tables BOTH
                # already on it -- a more direct, but ambiguous,
                # connection existed between path members, meaning this
                # "successful" route is likely circumventing exactly the
                # ambiguity this function exists to never silently
                # resolve.
                path_nodes = {root_table} | {h['to_table'] for h in new_path}
                for amb_from, amb_to, amb_cols in skipped_ambiguous:
                    if amb_from in path_nodes and amb_to in path_nodes:
                        raise ValueError(
                            f"Path from {root_table!r} to {target_table!r} found, but it "
                            f"routes around an ambiguous DIRECT connection between "
                            f"{amb_from!r} and {amb_to!r} ({len(amb_cols)} distinct FK "
                            f"columns: {amb_cols}) -- refusing a route that circumvents an "
                            f"unresolved ambiguity between two of its own members.")
                return new_path
            visited.add(nxt)
            queue.append((nxt, new_path))

        # Composite-key matches (see `composite_backward_edges`) are a
        # separate mechanism from the single-column edges above, so they
        # never enter `by_target`'s own ambiguity bookkeeping -- a
        # composite match is unambiguous by construction (it requires
        # EVERY column of the target's own PK to match), and only ever
        # supplies a target no ordinary single-column edge already
        # reached (skip if `nxt` is already in `by_target`, reachable, or
        # visited).
        #
        # Deliberately only tried at `current == root_table` (the FIRST
        # BFS node), never a few hops in -- a real ambiguity found testing
        # this against FLEX2's own `Graduation Eligibility`: without this
        # restriction, ANY table with an ordinary forward FK straight to
        # `root_table` (e.g. STUDENT_SEMESTER -> STUDENT_PROGRAM) would
        # transitively "reach" a composite target too (STUDENT_PROGRAM's
        # own composite match to BATCH_PROGRAM), manufacturing a second,
        # spurious root candidate that only reaches BATCH_PROGRAM by
        # routing THROUGH another table the decision already needs
        # directly (STUDENT_PROGRAM) -- not a genuine independent
        # junction the way `functional_backward_edges` chains legitimately
        # are. Restricting to the root itself matches both real motivating
        # cases exactly: `Graduation Eligibility`'s own root candidate IS
        # STUDENT_PROGRAM, and `Course Registration Eligibility`'s
        # upstream chaining (`drd_executor.py`) always calls
        # `build_join_path` with the decision's OWN subject table as
        # `root_table` already.
        if current != root_table:
            continue
        for edge in composite_backward_edges(case_study, current):
            nxt = edge['ref_table']
            if nxt not in allowed or nxt in visited or nxt in by_target:
                continue
            hop = {'from_table': current, 'from_columns': edge['columns'],
                   'to_table': nxt, 'to_columns': edge['ref_columns']}
            new_path = path + [hop]
            if nxt == target_table:
                return new_path
            visited.add(nxt)
            queue.append((nxt, new_path))

    # Deliberately just `None` here, not a raise naming the skipped
    # ambiguous edges: most of them (e.g. every table's own audit-trail
    # FKs to `users`) are nowhere near the actual target and naming one
    # as a probable cause would misattribute an unrelated failure.
    # `subject_table.py`'s own "cannot pick a unique root" error is
    # where a genuine ambiguity affecting the real answer gets surfaced.
    return None
