# This file is auto-generated from Spree Commerce's Rails migrations
# (spree/spree@main, squashed base migration 20210914000000_spree_four_three.rb
# + 276 incremental migrations since, parsed 2026-09-10).
#
# It is the schema.rb Spree does not ship natively, since Spree core is a Rails
# ENGINE (a gem), not a full application -- engines have no db/schema.rb of their
# own; the schema only exists as the sequence of migration files that a host app
# runs. This file is that sequence's cumulative result, reconstructed by a
# heuristic Ruby-migration parser (parse_spree_migrations.py), not generated by
# `rails db:schema:dump`.
#
# KNOWN LIMITATIONS, stated plainly:
# - Column types are as declared in the migration DSL, not resolved to full SQL
#   types with precision/scale.
# - Reference columns are rendered as plain `t.bigint "..._id"`.
# - Four parser edge cases were found and hand-corrected during generation
#   (documented, not silently fixed): `t.column :name, :type` DSL syntax
#   (spree_wishlists, spree_wishlist_items), `t.change` type-alteration calls
#   (spree_user_identities.info -> jsonb), and `t.remove` column deletions
#   (spree_newsletter_subscribers dropped public_metadata/private_metadata).
#   The parser itself was not patched for these forms; the schema data was
#   corrected by hand after verifying each against its source migration -- see
#   the session record for the exact corrections applied.
# - DEFAULT values are not tracked.
#

ActiveRecord::Schema.define do

  create_table "action_text_rich_texts", force: :cascade do |t|
    t.string "locale", null: false
  end

  create_table "friendly_id_slugs", force: :cascade do |t|
    t.string "slug", null: false
    t.bigint "sluggable_id", null: false
    t.string "sluggable_type"
    t.string "scope"
    t.datetime "created_at"
    t.datetime "deleted_at"
    t.string "locale"
    t.index [:slug, :sluggable_type, :locale]
    t.index [:slug, :sluggable_type, :scope, :locale], unique: true
    t.index :locale
    t.index [:slug, :sluggable_type, :locale]
    t.index [:slug, :sluggable_type, :scope, :locale], unique: true
  end

  create_table "spree_addresses", force: :cascade do |t|
    t.string "firstname"
    t.string "lastname"
    t.string "address1"
    t.string "address2"
    t.string "city"
    t.string "zipcode"
    t.string "phone"
    t.string "state_name"
    t.string "alternative_phone"
    t.string "company"
    t.bigint "state_id"
    t.bigint "country_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.datetime "deleted_at"
    t.string "label"
    t.boolean "quick_checkout"
    t.decimal "latitude"
    t.decimal "longitude"
    t.string "country_code"
    t.string "state_code"
    t.bigint "user_id"
    t.index :quick_checkout
    t.index :country_code
    t.index [:owner_type, :owner_id]
    t.index :user_id
  end

  create_table "spree_adjustments", force: :cascade do |t|
    t.string "source_type"
    t.bigint "source_id"
    t.string "adjustable_type"
    t.bigint "adjustable_id"
    t.decimal "amount"
    t.string "label"
    t.boolean "mandatory"
    t.boolean "eligible"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "state"
    t.bigint "order_id", null: false
    t.boolean "included"
    t.index :source_type
    t.index :amount
  end

  create_table "spree_admin_users", force: :cascade do |t|
    t.string "email", null: false
    t.string "password_digest"
    t.string "first_name"
    t.string "last_name"
    t.string "selected_locale"
    t.integer "failed_attempts"
    t.datetime "locked_at"
    t.index :email, unique: true
  end

  create_table "spree_allowed_origins", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "origin", null: false
    t.index [:store_id, :origin], unique: true
  end

  create_table "spree_api_keys", force: :cascade do |t|
    t.string "name", null: false
    t.string "key_type", null: false
    t.string "token", null: false
    t.bigint "store_id", null: false
    t.bigint "created_by_id"
    t.datetime "last_used_at"
    t.datetime "revoked_at"
    t.bigint "revoked_by_id"
    t.string "token_digest"
    t.string "token_prefix"
    t.json "scopes"
    t.index :token, unique: true
    t.index :key_type
    t.index [:store_id, :key_type]
    t.index :token_digest, unique: true
    t.index :token, unique: true
    t.index :token, unique: true
  end

  create_table "spree_calculators", force: :cascade do |t|
    t.string "type"
    t.string "calculable_type"
    t.bigint "calculable_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.text "preferences"
    t.datetime "deleted_at"
  end

  create_table "spree_carts", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "market_id", null: false
    t.bigint "channel_id", null: false
    t.bigint "customer_id"
    t.string "currency", null: false
    t.string "locale", null: false
    t.string "email"
    t.bigint "ship_address_id"
    t.bigint "bill_address_id"
    t.boolean "accept_marketing"
    t.text "customer_note"
    t.string "last_ip_address"
    t.string "token", null: false
    t.integer "lock_version"
    t.datetime "completed_at"
    t.datetime "completing_at"
    t.string "coupon_code"
    t.bigint "gift_card_id"
    t.bigint "preferred_stock_location_id"
    t.decimal "item_total"
    t.decimal "adjustment_total"
    t.decimal "included_tax_total"
    t.decimal "additional_tax_total"
    t.decimal "taxable_adjustment_total"
    t.decimal "non_taxable_adjustment_total"
    t.decimal "discount_total"
    t.decimal "fee_total"
    t.decimal "delivery_total"
    t.decimal "total"
    t.decimal "payment_total"
    t.integer "total_quantity"
    t.json "metadata"
    t.string "po_number"
    t.index :token, unique: true
    t.index :completed_at
    t.index :updated_at
  end

  create_table "spree_catalog_assignments", force: :cascade do |t|
    t.bigint "catalog_id", null: false
    t.bigint "assignable_id", null: false
    t.index [:catalog_id, :assignable_type, :assignable_id]
  end

  create_table "spree_catalog_order_minimums", force: :cascade do |t|
    t.bigint "catalog_id", null: false
    t.string "currency", null: false
    t.decimal "amount", null: false
    t.index [:catalog_id, :currency], unique: true
  end

  create_table "spree_catalog_products", force: :cascade do |t|
    t.bigint "catalog_id", null: false
    t.bigint "product_id", null: false
    t.index [:catalog_id, :product_id], unique: true
  end

  create_table "spree_catalog_quantity_rules", force: :cascade do |t|
    t.bigint "catalog_id", null: false
    t.bigint "variant_id", null: false
    t.integer "minimum_order_quantity"
    t.integer "order_multiple"
    t.index [:catalog_id, :variant_id], unique: true
  end

  create_table "spree_catalogs", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.boolean "active", null: false
    t.integer "position"
    t.json "metadata"
    t.text "description"
    t.integer "minimum_order_quantity"
    t.integer "order_multiple"
  end

  create_table "spree_categories", force: :cascade do |t|
    t.bigint "parent_id"
    t.integer "position"
    t.string "name", null: false
    t.string "permalink"
    t.bigint "taxonomy_id"
    t.bigint "lft"
    t.bigint "rgt"
    t.text "description"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "meta_title"
    t.string "meta_description"
    t.string "meta_keywords"
    t.integer "depth"
    t.boolean "hide_from_nav"
    t.string "pretty_name"
    t.string "rules_match_policy", null: false
    t.string "sort_order", null: false
    t.boolean "automatic", null: false
    t.integer "children_count", null: false
    t.integer "products_count", null: false
    t.index :pretty_name
    t.index :children_count
    t.index :classification_count
    t.index :products_count
  end

  create_table "spree_category_translations", force: :cascade do |t|
    t.string "name"
    t.text "description"
    t.string "locale", null: false
    t.bigint "spree_taxon_id", null: false
    t.string "meta_title"
    t.string "meta_description"
    t.string "meta_keywords"
    t.string "permalink"
    t.string "pretty_name"
    t.index :locale
    t.index [:spree_taxon_id, :locale], unique: true
    t.index :pretty_name
  end

  create_table "spree_channel_stock_locations", force: :cascade do |t|
    t.bigint "channel_id", null: false
    t.bigint "stock_location_id", null: false
  end

  create_table "spree_channels", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.string "code", null: false
    t.boolean "active", null: false
    t.text "preferences"
    t.boolean "default", null: false
    t.index :store_id, unique: true
  end

  create_table "spree_claim_line_items", force: :cascade do |t|
    t.bigint "claim_id", null: false
    t.bigint "line_item_id", null: false
    t.bigint "variant_id", null: false
    t.bigint "replacement_variant_id"
    t.integer "quantity", null: false
    t.boolean "send_replacement", null: false
    t.decimal "refund_amount", null: false
    t.text "description"
  end

  create_table "spree_claims", force: :cascade do |t|
    t.string "number", null: false
    t.bigint "store_id", null: false
    t.bigint "order_id", null: false
    t.bigint "reason_id"
    t.bigint "created_by_id"
    t.string "status", null: false
    t.string "resolution"
    t.text "memo"
    t.datetime "approved_at"
    t.datetime "resolved_at"
    t.datetime "denied_at"
    t.datetime "canceled_at"
    t.json "metadata"
    t.index :number, unique: true
    t.index :status
  end

  create_table "spree_collection_rules", force: :cascade do |t|
    t.bigint "collection_id", null: false
    t.string "type", null: false
    t.string "value"
    t.string "match_policy", null: false
    t.index [:collection_id, :type]
  end

  create_table "spree_collection_translations", force: :cascade do |t|
    t.string "name"
    t.string "permalink"
    t.string "meta_title"
    t.string "meta_description"
    t.string "meta_keywords"
    t.string "locale", null: false
    t.bigint "spree_collection_id", null: false
    t.text "description"
    t.index :locale
    t.index [:spree_collection_id, :locale], unique: true
  end

  create_table "spree_collections", force: :cascade do |t|
    t.string "name", null: false
    t.string "permalink"
    t.boolean "automatic", null: false
    t.string "rules_match_policy", null: false
    t.string "sort_order", null: false
    t.integer "position"
    t.integer "products_count", null: false
    t.bigint "store_id", null: false
    t.string "meta_title"
    t.string "meta_description"
    t.string "meta_keywords"
    t.json "metadata"
    t.text "description"
    t.index [:store_id, :permalink], unique: true
  end

  create_table "spree_commission_lines", force: :cascade do |t|
    t.bigint "order_id", null: false
    t.bigint "seller_id", null: false
    t.bigint "line_item_id"
    t.bigint "fulfillment_id"
    t.bigint "commission_rate_id"
    t.decimal "rate", null: false
    t.string "kind", null: false
    t.decimal "amount", null: false
    t.decimal "tax_amount", null: false
    t.decimal "tax_rate", null: false
    t.decimal "total", null: false
    t.string "currency", null: false
    t.string "taxability_reason"
    t.string "country_code"
    t.string "state_code"
    t.json "metadata"
    t.index [:seller_id, :created_at]
    t.index :taxability_reason
    t.index [:country_code, :state_code]
    t.index :line_item_id, unique: true
    t.index :fulfillment_id, unique: true
    t.check_constraint "(line_item_id IS NULL) <> (fulfillment_id IS NULL)"
  end

  create_table "spree_commission_rate_values", force: :cascade do |t|
    t.bigint "commission_rate_id", null: false
    t.string "currency", null: false
    t.decimal "amount", null: false
    t.decimal "min_amount"
    t.decimal "max_amount"
    t.datetime "deleted_at"
    t.index :deleted_at
    t.index [:commission_rate_id, :currency_key]
    t.index [:commission_rate_id, :currency]
  end

  create_table "spree_commission_rates", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.string "code"
    t.boolean "enabled", null: false
    t.integer "position", null: false
    t.string "kind", null: false
    t.decimal "value", null: false
    t.boolean "tax_inclusive", null: false
    t.boolean "include_shipping", null: false
    t.decimal "commission_tax_rate"
    t.json "metadata"
    t.datetime "deleted_at"
    t.index [:store_id, :enabled, :position]
    t.index :deleted_at
    t.index [:store_id, :code_key], unique: true
    t.index [:store_id, :code]
  end

  create_table "spree_commission_rule_products", force: :cascade do |t|
    t.bigint "commission_rule_id", null: false
    t.bigint "product_id", null: false
    t.datetime "deleted_at"
    t.index :deleted_at
    t.index [:commission_rule_id, :product_key]
    t.index [:commission_rule_id, :product_id]
  end

  create_table "spree_commission_rules", force: :cascade do |t|
    t.bigint "commission_rate_id", null: false
    t.string "type", null: false
    t.json "preferences"
    t.datetime "deleted_at"
    t.index :deleted_at
    t.index [:commission_rate_id, :type_key]
    t.index [:commission_rate_id, :type]
  end

  create_table "spree_companies", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "parent_id"
    t.string "name", null: false
    t.string "kind", null: false
    t.json "metadata"
    t.bigint "default_bill_address_id"
    t.bigint "default_ship_address_id"
    t.boolean "po_number_required", null: false
  end

  create_table "spree_company_invitations", force: :cascade do |t|
    t.bigint "company_id", null: false
    t.bigint "inviter_id"
    t.bigint "customer_id"
    t.string "email", null: false
    t.string "token", null: false
    t.datetime "expires_at", null: false
    t.datetime "accepted_at"
    t.datetime "revoked_at"
    t.json "metadata"
    t.index :token, unique: true
    t.index [:company_id, :email]
  end

  create_table "spree_company_memberships", force: :cascade do |t|
    t.bigint "company_id", null: false
    t.bigint "customer_id", null: false
    t.index [:company_id, :customer_id], unique: true
  end

  create_table "spree_consent_records", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "owner_id", null: false
    t.string "purpose", null: false
    t.string "source", null: false
    t.boolean "accepted", null: false
    t.string "email"
    t.string "ip_address"
    t.string "user_agent"
    t.json "documents"
    t.datetime "recorded_at", null: false
    t.index [:store_id, :purpose, :recorded_at]
    t.index 'LOWER
    t.index :email
  end

  create_table "spree_countries", force: :cascade do |t|
    t.string "iso_name"
    t.string "iso", null: false
    t.string "iso3", null: false
    t.string "name"
    t.integer "numcode"
    t.boolean "states_required"
    t.datetime "updated_at"
    t.boolean "zipcode_required"
    t.datetime "created_at"
  end

  create_table "spree_coupon_codes", force: :cascade do |t|
    t.string "code"
    t.bigint "promotion_id"
    t.bigint "order_id"
    t.integer "state", null: false
    t.datetime "deleted_at"
  end

  create_table "spree_credit_cards", force: :cascade do |t|
    t.string "month"
    t.string "year"
    t.string "cc_type"
    t.string "last_digits"
    t.bigint "address_id"
    t.string "gateway_customer_profile_id"
    t.string "gateway_payment_profile_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name"
    t.bigint "user_id"
    t.bigint "payment_method_id"
    t.boolean "default", null: false
    t.datetime "deleted_at"
    t.bigint "gateway_customer_id"
    t.index :gateway_customer_id
    t.index [:user_id, :payment_method_id, :fingerprint, :month, :year]
  end

  create_table "spree_custom_domains", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "url", null: false
    t.boolean "status"
    t.boolean "default", null: false
    t.json "public_metadata"
    t.json "private_metadata"
  end

  create_table "spree_custom_field_definitions", force: :cascade do |t|
    t.index [:store_id, :resource_type, :filter_key]
    t.index [:store_id, :resource_type, :namespace, :key]
    t.index [:resource_type, :namespace, :key], unique: true
  end

  create_table "spree_customer_group_users", force: :cascade do |t|
    t.bigint "customer_group_id", null: false
    t.bigint "user_id", null: false
  end

  create_table "spree_customer_groups", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.text "description"
    t.datetime "deleted_at"
    t.index [:store_id, :name], unique: true
    t.index :deleted_at
  end

  create_table "spree_customer_returns", force: :cascade do |t|
    t.string "number"
    t.bigint "stock_location_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "store_id"
  end

  create_table "spree_customers", force: :cascade do |t|
    t.string "email", null: false
    t.string "password_digest"
    t.string "first_name"
    t.string "last_name"
    t.string "phone"
    t.string "selected_locale"
    t.boolean "accepts_email_marketing", null: false
    t.bigint "bill_address_id"
    t.bigint "ship_address_id"
    t.integer "failed_attempts"
    t.datetime "locked_at"
    t.text "internal_note"
    t.datetime "email_marketing_consent_updated_at"
    t.string "email_marketing_consent_source"
    t.datetime "anonymized_at"
    t.index :email, unique: true
    t.index :bill_address_id
    t.index :ship_address_id
    t.index :accepts_email_marketing
  end

  create_table "spree_data_feeds", force: :cascade do |t|
    t.bigint "spree_store_id"
    t.string "name"
    t.string "provider"
    t.string "uuid"
    t.boolean "enabled"
    t.index [:store_id, :slug, :provider]
    t.index [:store_id, :name], unique: true
    t.index [:store_id, :slug], unique: true
  end

  create_table "spree_data_requests", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "customer_id", null: false
    t.string "number", null: false
    t.string "download_token"
    t.string "kind", null: false
    t.string "status", null: false
    t.string "email", null: false
    t.datetime "requested_at", null: false
    t.datetime "completed_at"
    t.datetime "expires_at"
    t.text "error_message"
    t.bigint "requested_by_id"
    t.index [:store_id, :number], unique: true
    t.index :download_token, unique: true
    t.index [:customer_id, :kind, :status]
    t.index :requested_by_id
  end

  create_table "spree_deliveries", force: :cascade do |t|
    t.bigint "owner_id", null: false
    t.bigint "store_id", null: false
    t.bigint "shipping_label_id"
    t.string "tracking_number", null: false
    t.string "tracking_url"
    t.string "carrier"
    t.string "service"
    t.string "status", null: false
    t.datetime "estimated_delivery_at"
    t.datetime "delivered_at"
    t.json "details"
    t.index [:store_id, :tracking_number]
    t.index [:owner_type, :owner_id, :tracking_number]
  end

  create_table "spree_delivery_method_rule_products", force: :cascade do |t|
    t.bigint "delivery_method_rule_id", null: false
    t.bigint "product_id", null: false
    t.index [:delivery_method_rule_id, :product_id]
  end

  create_table "spree_delivery_method_rules", force: :cascade do |t|
    t.string "type", null: false
    t.bigint "delivery_method_id", null: false
    t.boolean "active"
    t.json "preferences"
    t.index [:delivery_method_id, :type], unique: true
  end

  create_table "spree_delivery_method_services", force: :cascade do |t|
    t.bigint "delivery_method_id", null: false
    t.string "carrier", null: false
    t.string "service", null: false
    t.string "label"
    t.decimal "markup_flat"
    t.decimal "markup_percent"
    t.integer "position"
    t.index [:delivery_method_id, :carrier, :service]
  end

  create_table "spree_delivery_method_stock_locations", force: :cascade do |t|
    t.bigint "delivery_method_id", null: false
    t.bigint "stock_location_id", null: false
    t.index [:delivery_method_id, :stock_location_id]
  end

  create_table "spree_delivery_method_zones", force: :cascade do |t|
    t.bigint "shipping_method_id"
    t.bigint "zone_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.bigint "delivery_method_id", null: false
    t.bigint "delivery_zone_id", null: false
    t.index :delivery_method_id
    t.index :delivery_zone_id
  end

  create_table "spree_delivery_methods", force: :cascade do |t|
    t.string "name"
    t.string "display_on"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "tracking_url"
    t.string "admin_name"
    t.bigint "tax_category_id"
    t.string "code"
    t.integer "estimated_transit_business_days_min"
    t.integer "estimated_transit_business_days_max"
    t.boolean "storefront_visible", null: false
    t.string "fulfillment_provider"
    t.string "pickup_point_provider"
    t.string "rate_provider"
    t.decimal "markup_flat"
    t.decimal "markup_percent"
    t.string "fulfillment_type"
    t.boolean "available_to_sellers", null: false
    t.index :deleted_at
    t.index :tax_category_id
    t.index :fulfillment_type
  end

  create_table "spree_delivery_rates", force: :cascade do |t|
    t.bigint "shipment_id"
    t.bigint "shipping_method_id"
    t.boolean "selected"
    t.decimal "cost"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "tax_rate_id"
    t.string "carrier"
    t.string "service_level"
    t.date "estimated_delivery_date"
    t.json "metadata"
    t.string "name"
    t.boolean "unpriced", null: false
    t.index :selected
    t.index [:fulfillment_id, :delivery_method_id], unique: true
    t.index :fulfillment_id
    t.index :delivery_method_id
    t.index :tax_rate_id
    t.index [:fulfillment_id, :delivery_method_id]
  end

  create_table "spree_delivery_zone_members", force: :cascade do |t|
    t.bigint "delivery_zone_id", null: false
    t.string "member_type", null: false
    t.bigint "country_id"
    t.bigint "state_id"
    t.string "postal_code_prefix"
    t.string "postal_code_from"
    t.string "postal_code_to"
    t.string "country_code"
    t.string "state_code"
    t.index :country_code
  end

  create_table "spree_delivery_zones", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.string "description"
    t.json "metadata"
    t.index [:store_id, :name], unique: true
  end

  create_table "spree_digital_assets", force: :cascade do |t|
    t.string "provider_type"
    t.json "metadata"
  end

  create_table "spree_digital_links", force: :cascade do |t|
    t.bigint "digital_id"
    t.bigint "line_item_id"
    t.string "secret"
    t.integer "access_counter"
    t.index :secret, unique: true
  end

  create_table "spree_digitals", force: :cascade do |t|
    t.bigint "variant_id"
  end

  create_table "spree_discounts", force: :cascade do |t|
    t.bigint "cart_id"
    t.bigint "order_id"
    t.bigint "promotion_action_id"
    t.bigint "promotion_id"
    t.bigint "line_item_id"
    t.bigint "fulfillment_id"
    t.decimal "amount", null: false
    t.string "label", null: false
    t.string "kind", null: false
    t.string "code"
    t.decimal "value"
    t.string "value_type"
    t.json "metadata"
    t.index :code
    t.check_constraint "amount <= 0"
  end

  create_table "spree_exchange_line_items", force: :cascade do |t|
    t.bigint "exchange_id", null: false
    t.bigint "fulfillment_item_id", null: false
    t.bigint "line_item_id", null: false
    t.bigint "original_variant_id", null: false
    t.bigint "new_variant_id", null: false
    t.integer "quantity", null: false
    t.integer "received_quantity", null: false
    t.boolean "resellable", null: false
  end

  create_table "spree_exchanges", force: :cascade do |t|
    t.string "number", null: false
    t.bigint "store_id", null: false
    t.bigint "order_id", null: false
    t.bigint "stock_location_id", null: false
    t.bigint "reason_id"
    t.bigint "created_by_id"
    t.string "status", null: false
    t.text "memo"
    t.datetime "approved_at"
    t.datetime "received_at"
    t.datetime "fulfilled_at"
    t.datetime "canceled_at"
    t.json "metadata"
    t.index :number, unique: true
    t.index :status
  end

  create_table "spree_exports", force: :cascade do |t|
    t.bigint "user_id"
    t.bigint "store_id", null: false
    t.string "number", null: false
    t.string "type", null: false
    t.json "search_params"
    t.integer "format", null: false
    t.text "preferences"
    t.index [:store_id, :seller_id]
  end

  create_table "spree_external_references", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "system", null: false
    t.bigint "resource_id", null: false
    t.string "external_id", null: false
    t.json "metadata"
    t.index [:resource_type, :resource_id]
  end

  create_table "spree_fees", force: :cascade do |t|
    t.bigint "cart_id"
    t.bigint "order_id"
    t.bigint "line_item_id"
    t.bigint "fulfillment_id"
    t.decimal "amount", null: false
    t.string "label", null: false
    t.string "kind", null: false
    t.json "metadata"
    t.index [:order_id, :kind]
    t.check_constraint "amount >= 0"
  end

  create_table "spree_fulfillment_items", force: :cascade do |t|
    t.string "state"
    t.bigint "variant_id"
    t.bigint "order_id"
    t.bigint "shipment_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "pending"
    t.bigint "line_item_id"
    t.integer "quantity"
    t.bigint "original_return_item_id"
    t.index :line_item_id
    t.index :order_id
    t.index :original_return_item_id
    t.index :fulfillment_id
    t.index :variant_id
  end

  create_table "spree_fulfillments", force: :cascade do |t|
    t.string "tracking"
    t.string "number"
    t.decimal "cost"
    t.datetime "shipped_at"
    t.bigint "order_id"
    t.bigint "address_id"
    t.string "state"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "stock_location_id"
    t.decimal "adjustment_total"
    t.decimal "additional_tax_total"
    t.decimal "promo_total"
    t.decimal "included_tax_total", null: false
    t.decimal "pre_tax_amount", null: false
    t.decimal "taxable_adjustment_total", null: false
    t.decimal "non_taxable_adjustment_total", null: false
    t.json "public_metadata"
    t.json "private_metadata"
    t.string "fulfillment_type"
    t.json "pickup_point_data"
    t.datetime "delivered_at"
    t.index :address_id
    t.index :number, unique: true
    t.index :order_id
    t.index :stock_location_id
    t.index :tracking
    t.index :status
  end

  create_table "spree_gateway_customers", force: :cascade do |t|
    t.string "profile_id", null: false
    t.bigint "payment_method_id", null: false
    t.bigint "user_id", null: false
  end

  create_table "spree_gateways", force: :cascade do |t|
    t.string "type"
    t.string "name"
    t.text "description"
    t.boolean "active"
    t.string "environment"
    t.string "server"
    t.boolean "test_mode"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.text "preferences"
  end

  create_table "spree_gift_card_batches", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "created_by_id"
    t.integer "codes_count", null: false
    t.decimal "amount", null: false
    t.string "currency", null: false
    t.string "prefix"
    t.date "expires_at"
  end

  create_table "spree_gift_cards", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "user_id"
    t.bigint "gift_card_batch_id"
    t.bigint "created_by_id"
    t.string "code", null: false
    t.string "state", null: false
    t.decimal "amount", null: false
    t.decimal "amount_authorized", null: false
    t.decimal "amount_used", null: false
    t.string "currency", null: false
    t.date "expires_at"
    t.datetime "redeemed_at"
    t.index :code
  end

  create_table "spree_import_mappings", force: :cascade do |t|
    t.bigint "import_id", null: false
    t.string "schema_field", null: false
    t.string "file_column"
    t.index [:import_id, :schema_field], unique: true
  end

  create_table "spree_import_rows", force: :cascade do |t|
    t.bigint "import_id", null: false
    t.bigint "item_id"
    t.string "status", null: false
    t.integer "row_number", null: false
    t.text "data", null: false
    t.text "validation_errors"
    t.index [:import_id, :row_number], unique: true
    t.index [:import_id, :status]
  end

  create_table "spree_imports", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.bigint "owner_id", null: false
    t.string "status", null: false
    t.string "number", null: false
    t.string "type", null: false
    t.text "processing_errors"
    t.text "preferences"
    t.integer "rows_count", null: false
    t.integer "processing_groups_count"
    t.integer "completed_groups_count"
    t.index [:store_id, :seller_id]
  end

  create_table "spree_integrations", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "type", null: false
    t.text "preferences"
    t.boolean "active", null: false
    t.index [:store_id, :type], unique: true
  end

  create_table "spree_invitations", force: :cascade do |t|
    t.string "email", null: false
    t.string "token", null: false
    t.string "status", null: false
    t.bigint "resource_id", null: false
    t.bigint "inviter_id", null: false
    t.bigint "invitee_id"
    t.bigint "role_id", null: false
    t.datetime "accepted_at"
    t.datetime "expires_at"
    t.datetime "deleted_at"
  end

  create_table "spree_line_items", force: :cascade do |t|
    t.bigint "variant_id"
    t.bigint "order_id"
    t.integer "quantity", null: false
    t.decimal "price", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "currency"
    t.decimal "cost_price"
    t.bigint "tax_category_id"
    t.decimal "adjustment_total"
    t.decimal "additional_tax_total"
    t.decimal "promo_total"
    t.decimal "included_tax_total", null: false
    t.decimal "pre_tax_amount", null: false
    t.decimal "taxable_adjustment_total", null: false
    t.decimal "non_taxable_adjustment_total", null: false
    t.json "public_metadata"
    t.json "private_metadata"
    t.string "price_source"
  end

  create_table "spree_log_entries", force: :cascade do |t|
    t.string "source_type"
    t.bigint "source_id"
    t.text "details"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_market_countries", force: :cascade do |t|
    t.bigint "market_id", null: false
    t.bigint "country_id", null: false
    t.string "country_code"
    t.index [:market_id, :country_id], unique: true
    t.index [:market_id, :country_code]
  end

  create_table "spree_markets", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.string "currency", null: false
    t.string "default_locale", null: false
    t.string "supported_locales"
    t.boolean "tax_inclusive", null: false
    t.boolean "default", null: false
    t.integer "position", null: false
    t.datetime "deleted_at"
    t.string "tax_provider"
    t.index [:store_id, :name], unique: true
    t.index [:store_id, :default]
    t.index [:store_id, :position]
    t.index :deleted_at
  end

  create_table "spree_media", force: :cascade do |t|
    t.string "viewable_type"
    t.bigint "viewable_id"
    t.integer "attachment_width"
    t.integer "attachment_height"
    t.integer "attachment_file_size"
    t.integer "position"
    t.string "attachment_content_type"
    t.string "attachment_file_name"
    t.string "type"
    t.datetime "attachment_updated_at"
    t.text "alt"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string "session_id"
    t.string "media_type"
    t.decimal "focal_point_x"
    t.decimal "focal_point_y"
    t.string "external_video_url"
    t.index :media_type
  end

  create_table "spree_metafield_definitions", force: :cascade do |t|
    t.string "namespace", null: false
    t.string "key", null: false
    t.string "name", null: false
    t.string "metafield_type", null: false
    t.string "resource_type", null: false
    t.boolean "searchable"
    t.boolean "sortable"
    t.string "display_on", null: false
    t.index :display_on
  end

  create_table "spree_metafields", force: :cascade do |t|
    t.string "type", null: false
    t.bigint "resource_id", null: false
    t.bigint "metafield_definition_id", null: false
    t.text "value"
  end

  create_table "spree_newsletter_subscribers", force: :cascade do |t|
    t.string "email", null: false
    t.bigint "user_id"
    t.datetime "verified_at"
    t.string "verification_token"
    t.index [:email, :store_id], unique: true
    t.index :email, unique: true
  end

  create_table "spree_number_sequences", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "resource_type", null: false
    t.bigint "value", null: false
    t.index [:store_id, :resource_type]
  end

  create_table "spree_option_type_product_types", force: :cascade do |t|
    t.bigint "prototype_id"
    t.bigint "option_type_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:product_type_id, :option_type_id], unique: true
    t.index :option_type_id
  end

  create_table "spree_option_type_translations", force: :cascade do |t|
    t.string "presentation"
    t.string "locale", null: false
    t.bigint "spree_option_type_id", null: false
    t.index :locale
    t.index [:spree_option_type_id, :locale], unique: true
  end

  create_table "spree_option_types", force: :cascade do |t|
    t.string "name"
    t.string "presentation"
    t.integer "position", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "filterable", null: false
    t.string "kind", null: false
    t.index :name, unique: true
    t.index :kind
  end

  create_table "spree_option_value_translations", force: :cascade do |t|
    t.string "presentation"
    t.string "locale", null: false
    t.bigint "spree_option_value_id", null: false
    t.index :locale
    t.index [:spree_option_value_id, :locale], unique: true
  end

  create_table "spree_option_value_variants", force: :cascade do |t|
    t.bigint "variant_id"
    t.bigint "option_value_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "spree_option_values", force: :cascade do |t|
    t.integer "position"
    t.string "name"
    t.string "presentation"
    t.bigint "option_type_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "color_code"
  end

  create_table "spree_order_approvals", force: :cascade do |t|
    t.bigint "order_id", null: false
    t.string "status", null: false
    t.string "level"
    t.text "note"
    t.bigint "approver_id"
    t.datetime "decided_at"
    t.json "metadata"
    t.index [:order_id, :status]
    t.index [:approver_id, :approver_type]
  end

  create_table "spree_order_cancellations", force: :cascade do |t|
    t.bigint "order_id", null: false
    t.string "reason", null: false
    t.text "note"
    t.boolean "restock_items", null: false
    t.boolean "refund_payments", null: false
    t.decimal "refund_amount"
    t.boolean "notify_customer", null: false
    t.bigint "canceled_by_id"
    t.json "metadata"
    t.index :order_id
    t.index [:canceled_by_id, :canceled_by_type]
    t.index :created_at
  end

  create_table "spree_order_groups", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "customer_id"
    t.bigint "cart_id"
    t.string "number", null: false
    t.string "currency", null: false
    t.string "email"
    t.string "token"
    t.bigint "ship_address_id"
    t.bigint "bill_address_id"
    t.json "metadata"
    t.index :number, unique: true
    t.index [:store_id, :created_at]
    t.index :token
  end

  create_table "spree_order_promotions", force: :cascade do |t|
    t.bigint "order_id"
    t.bigint "promotion_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:promotion_id, :order_id], unique: true
  end

  create_table "spree_order_routing_rules", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "channel_id", null: false
    t.string "type", null: false
    t.integer "position", null: false
    t.boolean "active", null: false
    t.text "preferences"
    t.index [:channel_id, :position]
    t.index [:channel_id, :active, :position]
    t.index :type
    t.index [:channel_id, :type]
  end

  create_table "spree_orders", force: :cascade do |t|
    t.string "number"
    t.decimal "item_total", null: false
    t.decimal "total", null: false
    t.decimal "adjustment_total", null: false
    t.bigint "user_id"
    t.datetime "completed_at"
    t.bigint "bill_address_id"
    t.bigint "ship_address_id"
    t.decimal "payment_total"
    t.string "shipment_state"
    t.string "payment_state"
    t.string "email"
    t.text "special_instructions"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "currency"
    t.string "last_ip_address"
    t.bigint "created_by_id"
    t.decimal "shipment_total", null: false
    t.decimal "additional_tax_total"
    t.decimal "promo_total"
    t.string "channel"
    t.decimal "included_tax_total", null: false
    t.integer "item_count"
    t.bigint "approver_id"
    t.datetime "approved_at"
    t.boolean "confirmation_delivered"
    t.boolean "considered_risky"
    t.string "token"
    t.datetime "canceled_at"
    t.bigint "canceler_id"
    t.bigint "store_id"
    t.integer "state_lock_version", null: false
    t.decimal "taxable_adjustment_total", null: false
    t.decimal "non_taxable_adjustment_total", null: false
    t.boolean "store_owner_notification_delivered"
    t.json "public_metadata"
    t.json "private_metadata"
    t.text "internal_note"
    t.boolean "accept_marketing"
    t.boolean "signup_for_an_account"
    t.bigint "gift_card_id"
    t.string "locale"
    t.string "status"
    t.decimal "fee_total"
    t.string "coupon_code"
    t.string "po_number"
    t.decimal "commission_amount_total", null: false
    t.decimal "commission_tax_total", null: false
    t.decimal "commission_total", null: false
    t.index :gift_card_id
    t.index :status
    t.index :payment_status
    t.index :fulfillment_status
    t.index :coupon_code
    t.index :po_number
  end

  create_table "spree_package_types", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.string "kind", null: false
    t.decimal "length"
    t.decimal "width"
    t.decimal "height"
    t.string "dimensions_unit"
    t.decimal "weight"
    t.decimal "max_weight"
    t.string "weight_unit"
    t.boolean "default", null: false
    t.json "metadata"
    t.index [:store_id, :name], unique: true
    t.index :store_id, unique: true
    t.index [:store_id, :name], unique: true
    t.index [:store_id, :seller_id, :name], unique: true
    t.index :store_id, unique: true
    t.index [:store_id, :seller_id], unique: true
    t.index [:store_id, :seller_id, :name], unique: true
    t.index :store_id, unique: true
    t.index [:store_id, :name], unique: true
  end

  create_table "spree_payment_capture_events", force: :cascade do |t|
    t.decimal "amount"
    t.bigint "payment_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_payment_methods", force: :cascade do |t|
    t.string "type"
    t.string "name"
    t.text "description"
    t.boolean "active"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "auto_capture"
    t.text "preferences"
    t.integer "position"
    t.json "settings"
    t.string "capture_method"
    t.string "display_on"
  end

  create_table "spree_payment_methods_stores", id: false, force: :cascade do |t|
    t.bigint "payment_method_id"
    t.bigint "store_id"
  end

  create_table "spree_payment_sessions", force: :cascade do |t|
    t.string "type", null: false
    t.bigint "order_id", null: false
    t.bigint "payment_method_id", null: false
    t.bigint "customer_id"
    t.decimal "amount", null: false
    t.string "currency", null: false
    t.string "status", null: false
    t.string "external_id", null: false
    t.json "external_data"
    t.datetime "expires_at"
    t.string "customer_external_id"
    t.datetime "deleted_at"
    t.index [:order_id, :payment_method_id, :external_id]
    t.index :external_id
  end

  create_table "spree_payment_setup_sessions", force: :cascade do |t|
    t.bigint "customer_id"
    t.bigint "payment_method_id", null: false
    t.bigint "payment_source_id"
    t.string "status", null: false
    t.string "external_id"
    t.string "external_client_secret"
    t.json "external_data"
    t.datetime "deleted_at"
    t.string "type"
    t.index :status
    t.index [:external_id, :payment_method_id]
    t.index :type
  end

  create_table "spree_payment_sources", force: :cascade do |t|
    t.string "gateway_payment_profile_id"
    t.string "type"
    t.bigint "payment_method_id"
    t.bigint "user_id"
    t.json "public_metadata"
    t.json "private_metadata"
    t.string "gateway_customer_profile_id"
  end

  create_table "spree_payment_splits", force: :cascade do |t|
    t.bigint "payment_id", null: false
    t.bigint "order_id", null: false
    t.decimal "authorized_amount", null: false
    t.decimal "captured_amount", null: false
    t.decimal "refunded_amount", null: false
    t.string "currency", null: false
    t.decimal "claimed_amount"
    t.index [:payment_id, :order_id], unique: true
  end

  create_table "spree_payments", force: :cascade do |t|
    t.decimal "amount", null: false
    t.bigint "order_id"
    t.string "source_type"
    t.bigint "source_id"
    t.bigint "payment_method_id"
    t.string "state"
    t.string "response_code"
    t.string "avs_response"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "number"
    t.string "cvv_response_code"
    t.string "cvv_response_message"
    t.json "public_metadata"
    t.json "private_metadata"
    t.index [:order_id, :payment_method_id, :response_code]
    t.index [:order_id, :payment_method_id, :response_code]
  end

  create_table "spree_policies", force: :cascade do |t|
    t.string "slug", null: false
    t.string "name", null: false
    t.text "body"
    t.index [:store_id, :slug], unique: true
    t.index [:owner_id, :owner_type, :slug], unique: true
  end

  create_table "spree_policy_translations", force: :cascade do |t|
    t.string "locale", null: false
    t.string "name"
    t.bigint "spree_policy_id", null: false
    t.text "body"
    t.index [:spree_policy_id, :locale], unique: true
  end

  create_table "spree_preferences", force: :cascade do |t|
    t.text "value"
    t.string "key"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_price_adjustment_tiers", force: :cascade do |t|
    t.bigint "price_list_id", null: false
    t.integer "min_quantity", null: false
    t.decimal "percentage", null: false
    t.index [:price_list_id, :min_quantity]
  end

  create_table "spree_price_histories", force: :cascade do |t|
    t.bigint "price_id", null: false
    t.bigint "variant_id", null: false
    t.decimal "amount", null: false
    t.decimal "compare_at_amount"
    t.string "currency", null: false
    t.datetime "recorded_at", null: false
    t.datetime "created_at", null: false
    t.index [:variant_id, :currency, :recorded_at]
    t.index [:price_id, :recorded_at]
    t.index :recorded_at
  end

  create_table "spree_price_lists", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.text "description"
    t.integer "position", null: false
    t.string "status", null: false
    t.datetime "starts_at"
    t.datetime "ends_at"
    t.string "match_policy", null: false
    t.datetime "deleted_at"
    t.decimal "price_adjustment_percentage"
    t.boolean "adjust_compare_at", null: false
    t.index :status
    t.index :position
    t.index [:starts_at, :ends_at]
    t.index :deleted_at
    t.index [:store_id, :status, :position]
    t.index :catalog_key, unique: true
    t.index :catalog_id, unique: true
  end

  create_table "spree_price_rules", force: :cascade do |t|
    t.bigint "price_list_id", null: false
    t.string "type", null: false
    t.text "preferences"
    t.index [:price_list_id, :type]
    t.index :type
    t.index [:price_list_id, :type], unique: true
    t.index [:price_list_id, :type]
  end

  create_table "spree_prices", force: :cascade do |t|
    t.bigint "variant_id", null: false
    t.decimal "amount"
    t.string "currency"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.decimal "compare_at_amount"
    t.integer "min_quantity", null: false
    t.index [:variant_id, :currency, :price_list_id], unique: true
    t.index [:variant_id, :currency, :price_list_id]
    t.index [:variant_id, :currency]
    t.index [:variant_id, :currency, :price_list_id]
    t.index [:variant_id, :currency, :price_list_id, :min_quantity]
    t.index [:variant_id, :currency, :price_list_id, :min_quantity]
  end

  create_table "spree_product_categories", force: :cascade do |t|
    t.bigint "product_id"
    t.bigint "taxon_id"
    t.integer "position"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "spree_product_collections", force: :cascade do |t|
    t.bigint "product_id", null: false
    t.bigint "collection_id", null: false
    t.integer "position"
    t.index [:collection_id, :product_id], unique: true
  end

  create_table "spree_product_option_types", force: :cascade do |t|
    t.integer "position"
    t.bigint "product_id"
    t.bigint "option_type_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_product_promotion_rules", force: :cascade do |t|
    t.bigint "product_id"
    t.bigint "promotion_rule_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:product_id, :promotion_rule_id], unique: true
  end

  create_table "spree_product_publications", force: :cascade do |t|
    t.bigint "product_id", null: false
    t.bigint "channel_id", null: false
    t.datetime "published_at"
    t.datetime "unpublished_at"
  end

  create_table "spree_product_submissions", force: :cascade do |t|
    t.bigint "product_id", null: false
    t.string "status", null: false
    t.bigint "submitted_by_id"
    t.bigint "reviewed_by_id"
    t.datetime "reviewed_at"
    t.text "review_note"
    t.json "metadata"
    t.index [:product_id, :created_at]
  end

  create_table "spree_product_translations", force: :cascade do |t|
    t.string "name"
    t.text "description"
    t.string "locale", null: false
    t.bigint "spree_product_id", null: false
    t.text "meta_description"
    t.string "meta_keywords"
    t.string "meta_title"
    t.string "slug"
    t.datetime "deleted_at"
    t.index :locale
    t.index [:spree_product_id, :locale], unique: true
    t.index :deleted_at
    t.index [:locale, :slug], unique: true
  end

  create_table "spree_product_type_categories", force: :cascade do |t|
    t.bigint "taxon_id"
    t.bigint "prototype_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:product_type_id, :category_id], unique: true
    t.index :category_id
  end

  create_table "spree_product_type_custom_field_definitions", force: :cascade do |t|
    t.bigint "product_type_id", null: false
    t.bigint "custom_field_definition_id", null: false
    t.boolean "required", null: false
    t.integer "sort_order", null: false
  end

  create_table "spree_product_type_translations", force: :cascade do |t|
    t.string "name"
    t.string "locale", null: false
    t.bigint "spree_product_type_id", null: false
    t.index :locale
    t.index [:spree_product_type_id, :locale], unique: true
  end

  create_table "spree_product_types", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "products_count", null: false
    t.text "fulfillment_types"
  end

  create_table "spree_products", force: :cascade do |t|
    t.string "name", null: false
    t.text "description"
    t.datetime "available_on"
    t.datetime "deleted_at"
    t.string "slug"
    t.text "meta_description"
    t.string "meta_keywords"
    t.bigint "tax_category_id"
    t.bigint "shipping_category_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "promotionable"
    t.string "meta_title"
    t.datetime "discontinue_on"
    t.json "public_metadata"
    t.json "private_metadata"
    t.string "status", null: false
    t.datetime "make_active_at"
    t.integer "variant_count", null: false
    t.integer "classification_count", null: false
    t.integer "total_image_count", null: false
    t.bigint "thumbnail_id"
    t.integer "units_sold_count", null: false
    t.decimal "revenue", null: false
    t.bigint "default_variant_id"
    t.integer "collections_count", null: false
    t.index :status
    t.index :make_active_at
    t.index :promotionable
    t.index :variant_count
    t.index :classification_count
    t.index :total_image_count
    t.index :thumbnail_id
    t.index :default_variant_id
  end

  create_table "spree_products_stores", force: :cascade do |t|
    t.bigint "product_id"
    t.bigint "store_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "units_sold_count", null: false
    t.decimal "revenue", null: false
    t.index [:store_id, :units_sold_count]
    t.index [:store_id, :revenue]
  end

  create_table "spree_promotion_action_line_items", force: :cascade do |t|
    t.bigint "promotion_action_id"
    t.bigint "variant_id"
    t.integer "quantity"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:promotion_action_id, :variant_id], unique: true
  end

  create_table "spree_promotion_actions", force: :cascade do |t|
    t.bigint "promotion_id"
    t.integer "position"
    t.string "type"
    t.datetime "deleted_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "spree_promotion_categories", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "code"
  end

  create_table "spree_promotion_rule_categories", force: :cascade do |t|
    t.bigint "taxon_id"
    t.bigint "promotion_rule_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:taxon_id, :promotion_rule_id], unique: true
  end

  create_table "spree_promotion_rule_users", force: :cascade do |t|
    t.bigint "user_id"
    t.bigint "promotion_rule_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index [:user_id, :promotion_rule_id], unique: true
  end

  create_table "spree_promotion_rules", force: :cascade do |t|
    t.bigint "promotion_id"
    t.bigint "user_id"
    t.bigint "product_group_id"
    t.string "type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "code"
    t.text "preferences"
    t.index [:promotion_id, :type], unique: true
  end

  create_table "spree_promotions", force: :cascade do |t|
    t.string "description"
    t.datetime "expires_at"
    t.datetime "starts_at"
    t.string "name"
    t.string "type"
    t.integer "usage_limit"
    t.string "match_policy"
    t.string "code"
    t.boolean "advertise"
    t.string "path"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "promotion_category_id"
    t.string "code_prefix"
    t.integer "number_of_codes"
    t.integer "kind"
    t.boolean "multi_codes"
    t.index :kind
  end

  create_table "spree_promotions_stores", force: :cascade do |t|
    t.bigint "promotion_id"
    t.bigint "store_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_purchase_order_items", force: :cascade do |t|
    t.bigint "purchase_order_id", null: false
    t.bigint "variant_id", null: false
    t.integer "quantity_ordered", null: false
    t.integer "quantity_received", null: false
    t.decimal "unit_cost", null: false
    t.integer "quantity_rejected", null: false
    t.index [:purchase_order_id, :variant_id]
  end

  create_table "spree_purchase_orders", force: :cascade do |t|
    t.string "number", null: false
    t.string "status"
    t.string "currency", null: false
    t.string "reference"
    t.bigint "supplier_id", null: false
    t.bigint "store_id", null: false
    t.bigint "destination_location_id", null: false
    t.date "expected_at"
    t.datetime "ordered_at"
    t.datetime "received_at"
    t.text "notes"
    t.bigint "created_by_id"
    t.json "metadata"
    t.date "cancel_by"
    t.datetime "closed_short_at"
    t.text "close_reason"
    t.index :number, unique: true
    t.index :status
  end

  create_table "spree_refresh_tokens", force: :cascade do |t|
    t.string "token", null: false
    t.bigint "user_id", null: false
    t.datetime "expires_at", null: false
    t.string "ip_address"
    t.string "user_agent"
    t.string "audience"
    t.index :token, unique: true
    t.index :expires_at
    t.index [:user_type, :user_id]
  end

  create_table "spree_refund_reasons", force: :cascade do |t|
    t.string "name"
    t.boolean "active"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "mutable"
    t.index [:store_id, :name], unique: true
    t.index :name, unique: true
  end

  create_table "spree_refunds", force: :cascade do |t|
    t.bigint "payment_id"
    t.decimal "amount", null: false
    t.string "transaction_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "refund_reason_id"
    t.bigint "reimbursement_id"
    t.bigint "refunder_id"
    t.string "originator_type"
    t.bigint "originator_id"
    t.index :refunder_id
    t.index [:originator_type, :originator_id]
  end

  create_table "spree_reimbursement_credits", force: :cascade do |t|
    t.decimal "amount", null: false
    t.bigint "reimbursement_id"
    t.bigint "creditable_id"
    t.string "creditable_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "spree_reimbursement_types", force: :cascade do |t|
    t.string "name"
    t.boolean "active"
    t.boolean "mutable"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "type"
  end

  create_table "spree_reimbursements", force: :cascade do |t|
    t.string "number"
    t.string "reimbursement_status"
    t.bigint "customer_return_id"
    t.bigint "order_id"
    t.decimal "total"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_reports", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "user_id"
    t.string "type"
    t.string "currency"
    t.datetime "date_from"
    t.datetime "date_to"
  end

  create_table "spree_return_authorization_reasons", force: :cascade do |t|
    t.string "name"
    t.boolean "active"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "mutable"
    t.index [:store_id, :name], unique: true
    t.index :name, unique: true
  end

  create_table "spree_return_authorizations", force: :cascade do |t|
    t.string "number"
    t.string "state"
    t.bigint "order_id"
    t.text "memo"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.bigint "stock_location_id"
    t.bigint "return_authorization_reason_id"
  end

  create_table "spree_return_items", force: :cascade do |t|
    t.bigint "return_authorization_id"
    t.bigint "inventory_unit_id"
    t.bigint "exchange_variant_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.decimal "pre_tax_amount", null: false
    t.decimal "included_tax_total", null: false
    t.decimal "additional_tax_total", null: false
    t.string "reception_status"
    t.string "acceptance_status"
    t.bigint "customer_return_id"
    t.bigint "reimbursement_id"
    t.text "acceptance_status_errors"
    t.bigint "preferred_reimbursement_type_id"
    t.bigint "override_reimbursement_type_id"
    t.boolean "resellable", null: false
    t.index :fulfillment_item_id
  end

  create_table "spree_return_line_items", force: :cascade do |t|
    t.bigint "return_id", null: false
    t.bigint "fulfillment_item_id", null: false
    t.bigint "line_item_id", null: false
    t.bigint "variant_id", null: false
    t.integer "quantity", null: false
    t.integer "received_quantity", null: false
    t.decimal "pre_tax_amount", null: false
    t.boolean "resellable", null: false
  end

  create_table "spree_returns", force: :cascade do |t|
    t.string "number", null: false
    t.bigint "store_id", null: false
    t.bigint "order_id", null: false
    t.bigint "stock_location_id", null: false
    t.bigint "reason_id"
    t.bigint "created_by_id"
    t.string "status", null: false
    t.text "memo"
    t.datetime "approved_at"
    t.datetime "received_at"
    t.datetime "refunded_at"
    t.datetime "canceled_at"
    t.json "metadata"
    t.index :number, unique: true
    t.index :status
  end

  create_table "spree_role_users", force: :cascade do |t|
    t.bigint "role_id"
    t.bigint "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index :user_type
    t.index [:resource_id, :resource_type, :user_id, :user_type, :role_id], unique: true
  end

  create_table "spree_roles", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string "description"
    t.boolean "mutable", null: false
    t.json "permissions"
  end

  create_table "spree_seller_payouts", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "seller_id", null: false
    t.decimal "amount", null: false
    t.string "currency", null: false
    t.string "status", null: false
    t.datetime "period_start"
    t.datetime "period_end"
    t.string "provider", null: false
    t.string "reference"
    t.json "metadata"
    t.index [:seller_id, :currency, :status]
    t.index [:seller_id, :created_at]
    t.index [:provider, :reference], unique: true
    t.index [:provider, :reference], unique: true
  end

  create_table "spree_seller_requirement_custom_fields", force: :cascade do |t|
    t.bigint "seller_requirement_id", null: false
    t.bigint "custom_field_definition_id", null: false
  end

  create_table "spree_seller_requirement_submissions", force: :cascade do |t|
    t.bigint "seller_id", null: false
    t.bigint "seller_requirement_id", null: false
    t.string "status", null: false
    t.bigint "submitted_by_id"
    t.bigint "reviewed_by_id"
    t.datetime "reviewed_at"
    t.text "note"
    t.text "review_note"
    t.string "reference"
    t.json "metadata"
  end

  create_table "spree_seller_requirements", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "type", null: false
    t.string "name"
    t.text "description"
    t.integer "position", null: false
    t.boolean "active", null: false
    t.boolean "required", null: false
    t.text "preferences"
    t.json "metadata"
    t.index [:store_id, :position]
    t.index [:store_id, :type]
  end

  create_table "spree_seller_transfers", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.bigint "seller_id", null: false
    t.bigint "order_id", null: false
    t.bigint "payout_id"
    t.bigint "reversed_from_id"
    t.bigint "refund_id"
    t.decimal "amount", null: false
    t.string "currency", null: false
    t.string "kind", null: false
    t.string "status", null: false
    t.string "provider", null: false
    t.string "reference"
    t.json "metadata"
    t.index [:seller_id, :currency, :status]
    t.index [:seller_id, :created_at]
    t.index :refund_id, unique: true
    t.index :order_id, unique: true
    t.index :earning_key, unique: true
    t.index [:provider, :reference], unique: true
    t.index [:provider, :reference], unique: true
  end

  create_table "spree_seller_translations", force: :cascade do |t|
    t.string "name"
    t.text "about"
    t.string "locale", null: false
    t.bigint "spree_seller_id", null: false
    t.datetime "deleted_at"
    t.index :locale
    t.index [:spree_seller_id, :locale], unique: true
  end

  create_table "spree_sellers", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "name", null: false
    t.string "slug", null: false
    t.string "status", null: false
    t.string "contact_email"
    t.string "billing_email"
    t.text "about"
    t.bigint "billing_address_id"
    t.datetime "terms_accepted_at"
    t.datetime "holiday_mode_until"
    t.string "payouts_schedule_interval"
    t.decimal "minimum_payout_amount"
    t.string "tax_remittance", null: false
    t.json "metadata"
    t.datetime "deleted_at"
    t.string "legal_name"
    t.string "registration_number"
    t.datetime "payouts_enabled_at"
    t.index [:store_id, :slug], unique: true
    t.index [:store_id, :status]
    t.index :deleted_at
  end

  create_table "spree_shipping_categories", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index :type
  end

  create_table "spree_shipping_labels", force: :cascade do |t|
    t.bigint "owner_id", null: false
    t.bigint "store_id", null: false
    t.bigint "integration_id"
    t.string "source", null: false
    t.string "external_id"
    t.string "carrier"
    t.string "service"
    t.string "tracking_number"
    t.decimal "cost", null: false
    t.string "currency"
    t.string "format"
    t.string "status", null: false
    t.datetime "refunded_at"
    t.json "metadata"
    t.index [:owner_type, :owner_id]
    t.index [:owner_type, :owner_id]
  end

  create_table "spree_shipping_method_categories", force: :cascade do |t|
    t.bigint "shipping_method_id", null: false
    t.bigint "shipping_category_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_state_changes", force: :cascade do |t|
    t.string "name"
    t.string "previous_state"
    t.bigint "stateful_id"
    t.bigint "user_id"
    t.string "stateful_type"
    t.string "next_state"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_states", force: :cascade do |t|
    t.string "name"
    t.string "abbr"
    t.bigint "country_id"
    t.datetime "updated_at"
    t.datetime "created_at"
    t.index [:country_id, :abbr]
  end

  create_table "spree_stock_items", force: :cascade do |t|
    t.bigint "stock_location_id"
    t.bigint "variant_id"
    t.integer "count_on_hand", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "backorderable"
    t.datetime "deleted_at"
    t.json "public_metadata"
    t.json "private_metadata"
    t.index [:stock_location_id, :variant_id, :deleted_at], unique: true
  end

  create_table "spree_stock_levels", force: :cascade do |t|
    t.integer "allocated_count", null: false
  end

  create_table "spree_stock_locations", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "default", null: false
    t.string "address1"
    t.string "address2"
    t.string "city"
    t.bigint "state_id"
    t.string "state_name"
    t.bigint "country_id"
    t.string "zipcode"
    t.string "phone"
    t.boolean "active"
    t.boolean "backorderable_default"
    t.boolean "propagate_all_variants"
    t.string "admin_name"
    t.datetime "deleted_at"
    t.string "company"
    t.string "kind", null: false
    t.boolean "pickup_enabled", null: false
    t.string "pickup_stock_policy", null: false
    t.integer "pickup_ready_in_minutes"
    t.text "pickup_instructions"
    t.string "country_code"
    t.string "state_code"
    t.boolean "returns_enabled", null: false
    t.index :deleted_at
    t.index :pickup_enabled
    t.index :kind
    t.index :returns_enabled
  end

  create_table "spree_stock_movements", force: :cascade do |t|
    t.bigint "stock_item_id"
    t.integer "quantity"
    t.string "action"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "originator_type"
    t.bigint "originator_id"
    t.string "kind"
    t.string "reason"
    t.bigint "order_id"
    t.bigint "fulfillment_id"
    t.bigint "return_id"
    t.bigint "exchange_id"
    t.bigint "stock_transfer_id"
    t.bigint "purchase_order_id"
    t.decimal "unit_cost"
    t.bigint "stock_receipt_id"
    t.index :kind
    t.index :purchase_order_id
    t.index :stock_receipt_id
  end

  create_table "spree_stock_receipt_items", force: :cascade do |t|
    t.bigint "stock_receipt_id", null: false
    t.bigint "line_id", null: false
    t.integer "quantity_accepted", null: false
    t.integer "quantity_rejected", null: false
    t.string "rejection_reason"
    t.text "notes"
  end

  create_table "spree_stock_receipts", force: :cascade do |t|
    t.string "number", null: false
    t.bigint "store_id", null: false
    t.bigint "receivable_id", null: false
    t.string "reference"
    t.datetime "received_at", null: false
    t.bigint "received_by_id"
    t.text "notes"
    t.json "metadata"
    t.index :number, unique: true
    t.index :received_by_id
  end

  create_table "spree_stock_reservations", force: :cascade do |t|
    t.bigint "stock_item_id", null: false
    t.bigint "line_item_id", null: false
    t.bigint "order_id", null: false
    t.integer "quantity", null: false
    t.datetime "expires_at", null: false
    t.index [:stock_item_id, :expires_at]
    t.index [:stock_item_id, :line_item_id], unique: true
    t.index :expires_at
  end

  create_table "spree_stock_transfer_items", force: :cascade do |t|
    t.bigint "stock_transfer_id", null: false
    t.bigint "variant_id", null: false
    t.integer "quantity_shipped", null: false
    t.integer "quantity_received", null: false
    t.integer "quantity_rejected", null: false
    t.index [:stock_transfer_id, :variant_id]
  end

  create_table "spree_stock_transfers", force: :cascade do |t|
    t.string "reference"
    t.bigint "source_location_id"
    t.bigint "destination_location_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "number"
    t.json "public_metadata"
    t.json "private_metadata"
    t.bigint "store_id"
    t.string "status"
    t.datetime "shipped_at"
    t.datetime "received_at"
    t.text "notes"
    t.bigint "created_by_id"
    t.datetime "deleted_at"
    t.datetime "closed_short_at"
    t.text "close_reason"
    t.index :store_id
    t.index :status
    t.index :deleted_at
  end

  create_table "spree_store_credit_categories", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_store_credit_events", force: :cascade do |t|
    t.bigint "store_credit_id", null: false
    t.string "action", null: false
    t.decimal "amount"
    t.string "authorization_code", null: false
    t.decimal "user_total_amount", null: false
    t.bigint "originator_id"
    t.string "originator_type"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_store_credit_types", force: :cascade do |t|
    t.string "name"
    t.integer "priority"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_store_credits", force: :cascade do |t|
    t.bigint "user_id"
    t.bigint "category_id"
    t.bigint "created_by_id"
    t.decimal "amount", null: false
    t.decimal "amount_used", null: false
    t.text "memo"
    t.datetime "deleted_at"
    t.string "currency"
    t.decimal "amount_authorized", null: false
    t.bigint "originator_id"
    t.string "originator_type"
    t.bigint "type_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "store_id"
  end

  create_table "spree_store_translations", force: :cascade do |t|
    t.string "name"
    t.text "meta_description"
    t.text "meta_keywords"
    t.string "seo_title"
    t.string "facebook"
    t.string "twitter"
    t.string "instagram"
    t.string "customer_support_email"
    t.text "description"
    t.text "address"
    t.string "contact_phone"
    t.string "new_order_notifications_email"
    t.string "locale", null: false
    t.bigint "spree_store_id", null: false
    t.datetime "deleted_at"
    t.index :locale
    t.index [:spree_store_id, :locale], unique: true
    t.index :deleted_at
  end

  create_table "spree_stores", force: :cascade do |t|
    t.string "name"
    t.string "url"
    t.text "meta_description"
    t.text "meta_keywords"
    t.string "seo_title"
    t.string "mail_from_address"
    t.string "default_currency"
    t.string "code"
    t.boolean "default", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "supported_currencies"
    t.string "facebook"
    t.string "twitter"
    t.string "instagram"
    t.string "default_locale"
    t.string "customer_support_email"
    t.bigint "default_country_id"
    t.text "description"
    t.text "address"
    t.string "contact_phone"
    t.string "new_order_notifications_email"
    t.bigint "checkout_zone_id"
    t.string "seo_robots"
    t.string "supported_locales"
    t.datetime "deleted_at"
    t.json "settings"
    t.text "preferences"
    t.json "public_metadata"
    t.json "private_metadata"
    t.text "storefront_custom_code_head"
    t.text "storefront_custom_code_body_start"
    t.text "storefront_custom_code_body_end"
    t.string "default_country_code"
    t.string "setup_token"
    t.index :deleted_at
    t.index :setup_token, unique: true
  end

  create_table "spree_suppliers", force: :cascade do |t|
    t.string "name", null: false
    t.string "contact_name"
    t.string "email"
    t.string "phone"
    t.text "notes"
    t.bigint "store_id", null: false
    t.integer "purchase_orders_count", null: false
    t.string "address1"
    t.string "address2"
    t.string "city"
    t.string "state_name"
    t.string "state_code"
    t.string "country_code"
    t.string "postal_code"
    t.json "metadata"
    t.datetime "deleted_at"
    t.index [:store_id, :name], unique: true
    t.index :deleted_at
  end

  create_table "spree_taggings", force: :cascade do |t|
    t.bigint "tag_id"
    t.string "taggable_type"
    t.bigint "taggable_id"
    t.string "tagger_type"
    t.bigint "tagger_id"
    t.string "context"
    t.datetime "created_at"
    t.string "tenant"
  end

  create_table "spree_tags", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "taggings_count"
    t.index 'lower
  end

  create_table "spree_tax_categories", force: :cascade do |t|
    t.string "name"
    t.string "description"
    t.boolean "is_default"
    t.datetime "deleted_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "tax_code"
    t.index [:store_id, :name], unique: true
  end

  create_table "spree_tax_exemption_certificates", force: :cascade do |t|
    t.bigint "company_id", null: false
    t.string "country_code"
    t.string "state_code"
    t.string "certificate_number", null: false
    t.string "reason_code", null: false
    t.string "status", null: false
    t.datetime "issued_at"
    t.datetime "expires_at"
    t.string "issuing_authority"
    t.datetime "verified_at"
    t.bigint "verified_by_id"
    t.json "metadata"
    t.index [:company_id, :status]
    t.index [:country_code, :state_code]
  end

  create_table "spree_tax_identifiers", force: :cascade do |t|
    t.bigint "owner_id", null: false
    t.string "kind", null: false
    t.string "value", null: false
    t.string "validation_status"
    t.datetime "validated_at"
    t.json "validation_evidence"
    t.string "source"
    t.index [:owner_type, :owner_id, :kind]
  end

  create_table "spree_tax_lines", force: :cascade do |t|
    t.bigint "cart_id"
    t.bigint "order_id"
    t.bigint "tax_rate_id"
    t.bigint "line_item_id"
    t.bigint "fulfillment_id"
    t.bigint "fee_id"
    t.decimal "amount", null: false
    t.decimal "rate", null: false
    t.string "label", null: false
    t.boolean "included", null: false
    t.string "provider_id"
    t.json "data"
    t.json "metadata"
    t.string "taxability_reason"
    t.string "country_code"
    t.string "state_code"
    t.index :taxability_reason
    t.index [:country_code, :state_code]
  end

  create_table "spree_tax_rates", force: :cascade do |t|
    t.decimal "amount"
    t.bigint "zone_id"
    t.bigint "tax_category_id"
    t.boolean "included_in_price"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name"
    t.boolean "show_rate_in_label"
    t.datetime "deleted_at"
    t.json "public_metadata"
    t.json "private_metadata"
    t.string "country_code"
    t.string "state_code"
    t.index [:country_code, :state_code]
  end

  create_table "spree_taxon_rules", force: :cascade do |t|
    t.bigint "taxon_id", null: false
    t.string "type", null: false
    t.string "value", null: false
    t.string "match_policy", null: false
  end

  create_table "spree_taxonomies", force: :cascade do |t|
    t.string "name", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "position"
    t.bigint "store_id"
  end

  create_table "spree_taxonomy_translations", force: :cascade do |t|
    t.string "name"
    t.string "locale", null: false
    t.bigint "spree_taxonomy_id", null: false
    t.index :locale
    t.index [:spree_taxonomy_id, :locale], unique: true
  end

  create_table "spree_trackers", force: :cascade do |t|
    t.string "analytics_id"
    t.boolean "active"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "engine", null: false
  end

  create_table "spree_user_identities", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.string "provider", null: false
    t.string "uid", null: false
    t.jsonb "info"
    t.string "access_token"
    t.string "refresh_token"
    t.datetime "expires_at"
    t.index [:provider, :uid, :user_type], unique: true
  end

  create_table "spree_users", force: :cascade do |t|
    t.string "encrypted_password"
    t.string "password_salt"
    t.string "email"
    t.string "remember_token"
    t.string "persistence_token"
    t.string "reset_password_token"
    t.string "perishable_token"
    t.integer "sign_in_count", null: false
    t.integer "failed_attempts", null: false
    t.datetime "last_request_at"
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.string "login"
    t.bigint "ship_address_id"
    t.bigint "bill_address_id"
    t.string "authentication_token"
    t.string "unlock_token"
    t.datetime "locked_at"
    t.datetime "remember_created_at"
    t.datetime "reset_password_sent_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "spree_variant_media", force: :cascade do |t|
    t.bigint "variant_id", null: false
    t.bigint "media_id", null: false
    t.index [:variant_id, :media_id], unique: true
    t.index :media_id
  end

  create_table "spree_variants", force: :cascade do |t|
    t.string "sku", null: false
    t.decimal "weight"
    t.decimal "height"
    t.decimal "width"
    t.decimal "depth"
    t.datetime "deleted_at"
    t.boolean "is_master"
    t.bigint "product_id"
    t.decimal "cost_price"
    t.integer "position"
    t.string "cost_currency"
    t.boolean "track_inventory"
    t.bigint "tax_category_id"
    t.datetime "updated_at", null: false
    t.datetime "discontinue_on"
    t.datetime "created_at", null: false
    t.json "public_metadata"
    t.json "private_metadata"
    t.string "barcode"
    t.string "weight_unit"
    t.string "dimensions_unit"
    t.integer "image_count", null: false
    t.bigint "thumbnail_id"
    t.boolean "preorderable"
    t.datetime "preorder_ships_at"
    t.integer "backorder_limit"
    t.string "hs_code"
    t.string "country_of_origin"
    t.string "customs_description"
    t.integer "minimum_order_quantity"
    t.integer "order_multiple"
    t.string "purchase_unit"
    t.integer "units_per_carton"
    t.decimal "carton_weight"
    t.integer "cartons_per_pallet"
    t.index :barcode
    t.index :image_count
    t.index :thumbnail_id
  end

  create_table "spree_webhook_deliveries", force: :cascade do |t|
    t.bigint "webhook_endpoint_id", null: false
    t.string "event_name", null: false
    t.json "payload", null: false
    t.integer "response_code"
    t.text "response_body"
    t.string "error_type"
    t.integer "execution_time"
    t.text "request_errors"
    t.boolean "success"
    t.datetime "delivered_at"
    t.string "event_id"
    t.index [:webhook_endpoint_id, :event_id]
  end

  create_table "spree_webhook_endpoints", force: :cascade do |t|
    t.bigint "store_id", null: false
    t.string "url", null: false
    t.boolean "active", null: false
    t.json "subscriptions", null: false
    t.string "secret_key", null: false
    t.datetime "deleted_at"
    t.string "name"
    t.string "disabled_reason"
    t.datetime "disabled_at"
  end

  create_table "spree_wishlist_items", force: :cascade do |t|
    t.bigint "variant_id"
    t.bigint "wishlist_id"
    t.integer "quantity", null: false
    t.index [:variant_id, :wishlist_id], unique: true
    t.index :variant_id
    t.index :wishlist_id
  end

  create_table "spree_wishlists", force: :cascade do |t|
    t.bigint "user_id"
    t.bigint "store_id"
    t.string "name"
    t.string "token", null: false
    t.boolean "is_private", null: false
    t.boolean "is_default", null: false
    t.index :token, unique: true
    t.index [:user_id, :is_default]
  end

  create_table "spree_zone_members", force: :cascade do |t|
    t.string "zoneable_type"
    t.bigint "zoneable_id"
    t.bigint "zone_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index [:zone_id, :zoneable_type, :zoneable_id]
    t.index [:zoneable_id, :zoneable_type]
  end

  create_table "spree_zones", force: :cascade do |t|
    t.string "name"
    t.string "description"
    t.boolean "default_tax"
    t.integer "zone_members_count"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "kind"
  end

  add_foreign_key "spree_category_translations", "spree_taxon"
  add_foreign_key "spree_option_type_translations", "spree_option_type"
  add_foreign_key "spree_option_value_translations", "spree_option_value"
  add_foreign_key "spree_product_translations", "spree_product"
  add_foreign_key "spree_store_translations", "spree_store"
  add_foreign_key "spree_taxonomy_translations", "spree_taxonomy"

end